'use strict';
const crypto = require('crypto');
const User = require('../models/User');
const { isDbConnected } = require('../config/db');
const scrypt = (password,salt)=>new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(e,k)=>e?reject(e):resolve(k.toString('hex'))));
const tokenHash = token => crypto.createHash('sha256').update(token).digest('hex');
function cookie(req,name){ const raw=req.headers.cookie||''; const item=raw.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'=')); return item?decodeURIComponent(item.slice(name.length+1)):null; }
function publicUser(u){return {id:u._id,name:u.name,loginId:u.loginId,patientId:u.patientId,role:u.role||'patient',location:u.location||null,selectedPhc:u.selectedPhc||null};}
function setSession(res,token,remember){ const maxAge=remember?60*60*24*30:60*60*12; res.setHeader('Set-Cookie',`gac_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${process.env.NODE_ENV==='production'?'; Secure':''}`); return maxAge; }
async function createSession(user,res,remember){const token=crypto.randomBytes(32).toString('hex'); const maxAge=setSession(res,token,remember); user.sessionTokenHash=tokenHash(token); user.sessionExpiresAt=new Date(Date.now()+maxAge*1000); await user.save();}
async function register(req,res,next){try{if(!isDbConnected())return res.status(503).json({success:false,message:'Database is temporarily unavailable. Please try again shortly.'}); const {name,loginId,password,remember=false,location=null,role='patient'}=req.body||{}; if(!['patient','asha'].includes(role))return res.status(400).json({success:false,message:'Choose Patient or ASHA worker.'}); if(!name||!loginId||typeof password!=='string'||password.length<8)return res.status(400).json({success:false,message:'Name, phone/email, and a password of at least 8 characters are required.'}); const id=String(loginId).trim().toLowerCase(); if(await User.exists({loginId:id}))return res.status(409).json({success:false,message:'An account already exists for this phone/email.'}); const salt=crypto.randomBytes(16).toString('hex'); const passwordHash=await scrypt(password,salt); const user=await User.create({name:String(name).trim(),loginId:id,passwordHash,passwordSalt:salt,patientId:`PID-GAC-${crypto.randomBytes(5).toString('hex').toUpperCase()}`,role,location:location||undefined}); await createSession(user,res,remember); return res.status(201).json({success:true,data:publicUser(user)});}catch(e){next(e)}}
async function login(req,res,next){try{if(!isDbConnected())return res.status(503).json({success:false,message:'Database is temporarily unavailable.'}); const {loginId,password,remember=false}=req.body||{}; const user=await User.findOne({loginId:String(loginId||'').trim().toLowerCase()}); if(!user)return res.status(401).json({success:false,message:'Incorrect login details.'}); const hash=await scrypt(String(password||''),user.passwordSalt); const ok=crypto.timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(user.passwordHash,'hex')); if(!ok)return res.status(401).json({success:false,message:'Incorrect login details.'}); await createSession(user,res,remember); return res.json({success:true,data:publicUser(user)});}catch(e){next(e)}}
async function requireAuth(req,res,next){try{if(!isDbConnected())return res.status(503).json({success:false,message:'Database unavailable.'}); const token=cookie(req,'gac_session'); if(!token)return res.status(401).json({success:false,message:'Login required.'}); const user=await User.findOne({sessionTokenHash:tokenHash(token),sessionExpiresAt:{$gt:new Date()}}); if(!user)return res.status(401).json({success:false,message:'Session expired. Please log in again.'}); req.user=user; next();}catch(e){next(e)}}
async function me(req,res){res.json({success:true,data:publicUser(req.user)})}
async function logout(req,res,next){try{req.user.sessionTokenHash=null;req.user.sessionExpiresAt=null;await req.user.save();res.setHeader('Set-Cookie','gac_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({success:true});}catch(e){next(e)}}
async function saveLocation(req,res,next){try{const {lat,lng,accuracy,selectedPhc}=req.body||{}; const hasLocation=Number.isFinite(lat)&&Number.isFinite(lng); if((lat!==undefined||lng!==undefined)&&(!hasLocation||lat<-90||lat>90||lng<-180||lng>180))return res.status(400).json({success:false,message:'Invalid location.'}); if(hasLocation) req.user.location={lat,lng,accuracy:Number(accuracy)||null,updatedAt:new Date()}; if(selectedPhc)req.user.selectedPhc=selectedPhc; await req.user.save();res.json({success:true,data:publicUser(req.user)});}catch(e){next(e)}}
module.exports={register,login,requireAuth,me,logout,saveLocation};
